version: '3.8'

services:
  backend-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/homegrow
      - JWT_SECRET=homegrow_development_secret_key
      - JWT_EXPIRES_IN=7d
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - mongo
    networks:
      - test-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-test-data:/data/db
      - ../database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  mongo-test-data:
